### ISSUE TITLE
Does not work with SveltKit

### ISSUE THREAD

**Issue by pinwaven** [vikignt/svelte-ui#47]
The components do not work with the most recenlty version of SvelteKit

4:29:52 PM [vite] hmr update /src/routes/ehr/+page.svelte
[ '12', [ false, true, false, false, false ], [ false, false, false ] ]
Error: <Datefield> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <Datefield>.
    at Module.validate_component (/node_modules/svelte/internal/index.mjs:1869:15)
    at eval (/src/routes/ehr/+page.svelte:131:25)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at Object.default (root.svelte:41:38)
    at eval (/src/routes/+layout.svelte:22:67)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at root.svelte:40:37
    at $$render (/node_modules/svelte/internal/index.mjs:1892:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:1900:26)
    at Module.render_response (/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:115:27)
4:45:13 PM [vite-plugin-svelte] ssr compile done.

**Comment by vikignt** [comment]
Thank you @pinwaven . I will try to adapt it for sveltekit, I need to find the time.
